### ISSUE TITLE
Blind rolls aren't being tracked even though the setting is checked on.

### ISSUE THREAD

**Issue by Joshmvii7** [drexl93/roll-tracker#1]
PF2E system if it matters. I have the setting checked to count Blind Rolls, but they're not being counted.

**Comment by drexl93** [comment]
For clarification: do you mean Blind Rolls that a player makes are not counted, Blind Rolls that a GM makes are not counted, or all Blind Rolls?

**Comment by Joshmvii7** [comment]
It's both. PF2E system does the game's Secret checks as Blind GM Rolls, and when those are rolled they aren't being counted in the tracking.

**Comment by drexl93** [comment]
Fixed in the latest release! If you're still seeing an issue after updating, please open up another issue. Thank you for the feedback!
