### ISSUE TITLE
V10 Support

### ISSUE THREAD

**Issue by Thilenios** [drexl93/roll-tracker#13]
It seems like it doesn't currently support the newest V10 version? I am getting the following error in the console when I make a roll, and nothing is tracked.
![image](https://user-images.githubusercontent.com/12223348/236892664-9a8d6f49-8e2e-4392-a20b-0f98c04619cd.png)

**Comment by drexl93** [comment]
Hmm... I'm not seeing that error message. I'm testing on Foundry V10 Build 291, on both PF2e and DnD5e, and it seems to record rolls just fine. Could you perhaps provide some more information about what system you're running it on, what other modules you have enabled, and what rolls you're making?

**Comment by Thilenios** [comment]
I am running the latest V10 on Forge with the Lancer systen. I have a large selection of mods installed, so hard to Share a list. Oddly, today, I reupdated everything and it seems to be tracking fine.

Seems like the issue can be closed as I can't repeat it today either.
