### ISSUE TITLE
Only tracking for some of my players 

### ISSUE THREAD

**Issue by thejoester** [drexl93/roll-tracker#15]
So some of my players it _seems_ ti work others it does not. One player is rolling from DnDBeyond with the Beyond20 plugin and it is tracking his rolls but not a couple players rolling straight from their character sheets. Not seeing errors in the console.

**Comment by drexl93** [comment]
Are you using any other modules that affect rolling behaviour like Midi QoL?

**Comment by thejoester** [comment]
Sorry took a while to test, and what I found was it seemed it was tracking for a short time then stopped. After trial and error and making a new world to test my other modules one by one it seems the issue is Roll Tracker will not track when Ready Set Rollfor 5E is enabled.
