### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by cauterize** [drexl93/roll-tracker#16]
Got a warning in foundry:

```
foundry.js:68326 Roll Tracker is unmaintained and may introduce stability issues to your game.
fetch @ foundry.js:68326
```

**Comment by cauterize** [comment]
Okay, thanks.

I mainly opened the issue for you so you know foundry falsely reports your module as unmaintained.

I will keep on ignoring the warning then.

**Comment by drexl93** [comment]
Thanks for bringing it to my attention! Should be fixed in the latest release.
