### ISSUE TITLE
Median is not calculated correctly

### ISSUE THREAD

**Issue by jocolamarco** [drexl93/roll-tracker#2]
version: 1.4.0

In the simple example below, the median is shown as 15, whereas it should be 14:

![image](https://user-images.githubusercontent.com/45291719/158070986-ff1b8350-e092-4925-b2d3-25b7edc6f3e1.png)

You can easily verify manually or with the help of a tool.
![image](https://user-images.githubusercontent.com/45291719/158070966-71c4b9d5-d80b-4ba1-b2fc-adcf30a179d6.png)

**Comment by drexl93** [comment]
Fixed in the latest release! If you're still seeing an issue after updating, please open up another issue. Thank you for the feedback!
