### ISSUE TITLE
Support for Pathfinder 1e Attack Rolls

### ISSUE THREAD

**Issue by lisosaurus** [drexl93/roll-tracker#3]
I'm guessing the Pathfinder 1e system does their attack cards differently than most systems, and therefore these rolls aren't being tracked. Is there any way you could add support for this system?

[Screenshot](https://i.imgur.com/E9F9qcF.png)

**Comment by drexl93** [comment]
Hey, I took a look at the PF1e code and the troublesome thing is that the data (for what was rolled on the dice) seems to be located in different places depending on the type of roll (save vs attack). That means it'd be more than just a quick fix to support the system. There's probably someone who knows a lot more about the system and knows a better way to do it - if they're interested in forking this project or pointing me in a better direction, I'd be happy to include it. Unfortunately I don't have the time or expertise to do it myself at this time.
