### ISSUE TITLE
Latest version not working in Foundry V9

### ISSUE THREAD

**Issue by JudgeNash** [drexl93/roll-tracker#9]

**Comment by JudgeNash** [comment]
Hey. Thanks so much for adding the roll counter, but sadly once I update, the module no longer appears in my world - Foundry V9.
Cheers

**Comment by drexl93** [comment]
Sorry about that, my mistake on not properly indicating the compatibility with the latest releases. I've created a fork of the module that should be the same version that worked for you on V9. You'll need to install it via direct manifest file: https://raw.githubusercontent.com/drexl93/roll-tracker/version-9/module.json

Let me know if that works for you.

**Comment by JudgeNash** [comment]
Hi there.
Thanks for replying! So I removed the module I had, then reinstalled using the link you gave me, the app reinstalled, but still can’t see the Total Rolls number if I should? Here’s what I see for me...
Again, thank you so much for spending time on this.
Cheers,
Craig
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by drexl93** [comment]
That's right, the code for the Total Rolls number is bundled with the latest version that only works on Foundry V10, and not V9. So unfortunately you won't be able to see that feature right now (but you can at least continue using the module), but once you upgrade your Foundry version to V10 and update the module, it'll be there.
